### ISSUE TITLE
NetIPInterface Add the possibility to modify the MTU

### ISSUE THREAD

**Issue by Erwan-loot** [dsccommunity/NetworkingDsc#460]
Hello,

By referring to this documentation https://docs.microsoft.com/en-us/powershell/module/nettcpip/set-netipinterface?view=win10-ps, where this resource has many similarities, we can change the MTU effectively with powershell. Unfortunately, I haven't figured out how to do it with the DSC Networking module.

**Comment by PlagueHO** [comment]
Hi @Erwan-loot - looks like we don't have this feature in the `NetIpInterface` resource (where I'd expect it to be). Should be easy enough to add the feature to this resource. I'll open it up for community contribution otherwise I'll add it.

**Comment by Erwan-loot** [comment]
Thanks to your reply

i use ansible et actually i use something like this

```yaml
- name: Check MTU of the interface {{ interface_renamed.stdout|trim }}
  win_shell: "(Get-NetIPInterface -InterfaceAlias {{ interface_renamed.stdout|trim }}).NlMtu"
  changed_when: False
  register: mtu


- name: Change MTU of the interface {{ interface_renamed.stdout|trim }} on IPv4 from {{ mtu.stdout|trim }} bytes to {{ mtu_size }} bytes
  win_shell: "Set-NetIPInterface -InterfaceAlias {{ interface_renamed.stdout|trim }} -NlMtuBytes {{ mtu_size }} -AddressFamily 'IPv4' "
  changed_when: mtu.stdout|trim != mtu_size
```
Wokrs but not idempotent
